const UnityContent = {
  pageId: 'Unity',
  buttonText: 'Projects - Unity Development',
  aspectRatio: '16:9',
  content: [
    {
      layoutNumber: 1,
      position: { row: 1, column: 1 },
      offset: { x: 0, y: 0 },
      size: { width: 150, height: 25 },
      sizeType: 'auto',
      type: 'title',
      src: `Meteor Storm - C#/Unity`,
    },
    {
      layoutNumber: 2,
      position: { row: 1, column: 2 },
      offset: { x: 0, y: 0 },
      size: { width: 1, height: 1 },
      sizeType: 'fixed',
      type: 'blank',
    },
    {
      layoutNumber: 3,
      position: { row: 3, column: 2 },
      offset: { x: 0, y: 10 },
      size: { width: 85, height: 85 },
      sizeType: 'auto',
      clamp: 320,
      type: 'image',
      src: {
        src: '../meteor-storm.jpg',
        alt: `Screen grab of in-game action from my Unity game`,
      },
    },
    {
      layoutNumber: 4,
      position: { row: 2, column: 2 },
      offset: { x: 0, y: 0 },
      size: { width: 100, height: 125 },
      sizeType: 'grow',
      type: 'html',
      src: `<h2>The process I went through when I considered games programming</h2>
      <p>Having been floundering around a bit trying to find my way back into development over the past several years I was excited to be accepted onto a bootcamp that offered a possible job opportunity that I hadn't even considered - computer games. I hoped that my non-gamer perspective might be appreciated and fresh so I excitedly began my on-boarding. As I went through the Unity Junior Programmer Pathway and a few units of the Unity Creative Core Pathway I started this project as my prototype and a place to get aquainted with another new language.</p>`,
    },
    {
      layoutNumber: 5,
      position: { row: 3, column: 1 },
      offset: { x: 0, y: 5 },
      size: { width: 100, height: 185 },
      sizeType: 'grow',
      type: 'html',
      src: `<h2>The joy of creating my own game as I learned</h2>
      <p>Please check out the <a href="https://play.unity.com/en/games/450a5269-15ef-478c-8585-44ba69997472/meteor-storm" target="_blank">WebGL build</a> if you've got a spare moment to play (it's not suitable for mobiles I'm afraid).</p>
      <p>I continued to use this project for learning as I worked my way through the 12 week Unity bootcamp and towards my offcial Unity certification exam. I created it as a playground to start with, and so the code got quite ugly in it's early stages, but through refactoring and learning more and more of the working methods and intricacies of C# it became a great product of the learning experience. I discovered that I really liked working with C# and it also helped me to become a little more comfortable with object oriented principles. It's just a little space shooter game but it became quite playable and taught me a lot about the basics of game development, although I did become aware that my lack of experience of actually playing games was going to be an obstacle. It contains my first attempt at implementing a score and leaderboard system along with all of the UI basics, player controls, asset creation, ray-casting, and a game manager.
</p>`,
    },
    {
      layoutNumber: 6,
      position: { row: 2, column: 1 },
      offset: { x: 50, y: 30 },
      size: { width: 30, height: 50 },
      sizeType: 'auto',
      clamp: 160,
      type: 'image',
      src: {
        src: '../unity-certified-associate-programmer.png',
        alt: `I am a Unity certified programmer at associate level`,
      },
    },
    {
      layoutNumber: 7,
      position: { row: 2, column: 1 },
      offset: { x: 50, y: 50 },
      size: { width: 30, height: 50 },
      sizeType: 'auto',
      clamp: 160,
      type: 'image',
      src: {
        src: '../skills-city-immersive-technologies-gold.png',
        alt: `I also received a Gold Award from the bootcamp`,
      },
    },
    {
      layoutNumber: 8,
      position: { row: 3, column: 2 },
      offset: { x: 20, y: 0 },
      size: { width: 80, height: 15 },
      sizeType: 'grow',
      type: 'title',
      src: `check out the <a aria-label="Visit the GitHub repo for this project" href="https://github.com/gileswebberley/Meteor-Storm" target="_blank">source code</a> on GitHub`,
    },
    {
      layoutNumber: 13,
      position: { row: 4, column: 1 },
      offset: { x: 0, y: 0 },
      size: { width: 100, height: 10 },
      sizeType: 'fixed',
      type: 'blank',
    },
    {
      layoutNumber: 9,
      position: { row: 5, column: 1 },
      offset: { x: 0, y: 0 },
      size: { width: 150, height: 25 },
      sizeType: 'auto',
      type: 'title',
      src: `Cypher - C#/Unity</p>`,
    },
    {
      layoutNumber: 10,
      position: { row: 6, column: 2 },
      offset: { x: 0, y: 0 },
      size: { width: 35, height: 85 },
      sizeType: 'auto',
      clamp: 120,
      type: 'image',
      src: {
        src: '../cypher.gif',
        alt: `Screen grab of cypher original usage`,
      },
    },
    {
      layoutNumber: 11,
      position: { row: 6, column: 1 },
      offset: { x: 5, y: 0 },
      size: { width: 90, height: 165 },
      sizeType: 'grow',
      type: 'html',
      src: `<h2>A little challenge that became another tool for learning, and a good system for game based puzzles</h2>
      <p>We were set this problem on my bootcamp to create a simple cypher program in C# and then use it within a Unity project. I enjoyed helping others who weren't so comfortable with programming (they were generally great 3d artists which they helped me understand in return) whilst also learning loads of new things myself. I improved and extended the project as I find tinkering, problem solving, and making mistakes a wonderful learning process. I continued developing it to create a puzzle-solving event system which my friends on the course could use in their own games, one example of usage was to open a door in an escape game which was very satisfying to see.</p>`,
    },
    {
      layoutNumber: 12,
      position: { row: 6, column: 2 },
      offset: { x: 0, y: 20 },
      size: { width: 60, height: 25 },
      sizeType: 'grow',
      type: 'title',
      src: `check out the <a aria-label="Visit the GitHub repo for this project" href="https://github.com/gileswebberley/Cypher" target="_blank">source code</a> on GitHub`,
    },
  ],
};
export default UnityContent;
