const WelcomeContent = {
  pageId: 'Welcome',
  buttonText: 'Project - This Site',
  aspectRatio: '16:9',
  content: [
    {
      layoutNumber: 1,
      position: { row: 1, column: 1 },
      offset: { x: 0, y: 0 },
      size: { width: 150, height: 25 },
      sizeType: 'auto',
      type: 'title',
      src: `Gilo_Does_Coding - JS/HTML5/CSS3`,
    },
    {
      layoutNumber: 3,
      position: { row: 2, column: 1 },
      offset: { x: 10, y: 0 },
      size: { width: 50, height: 60 },
      sizeType: 'auto',
      clamp: 250,
      type: 'image',
      src: {
        src: '../pageObjectDef.jpg',
        alt: `image of the definition of this sites page object`,
      },
    },
    {
      layoutNumber: 9,
      position: { row: 2, column: 1 },
      offset: { x: 0, y: 20 },
      size: { width: 40, height: 15 },
      sizeType: 'auto',
      clamp: 170,
      type: 'title',
      src: `<a href="https://github.com/gileswebberley/gilo-does-coding/blob/main/src/contents/ContentTemplateExample.js" target="_blank">what makes a page</a>`,
    },
    {
      layoutNumber: 7,
      position: { row: 2, column: 2 },
      offset: { x: 0, y: 0 },
      size: { width: 100, height: 100 },
      sizeType: 'grow',
      type: 'html',
      src: `<h2>"What is this nonsense!?"</h2>
      <p>I imagine you're wondering what on earth is going on with all these floaty things ambling around the screen, although I hope you like it? Do please resize your browser to see how the layout manager responds if you're on a desktop, and also be aware that the colour scheme is based on your browser preference along with the time of day (I'm a child of the 70s btw so hence my love of orange tones!!). You can toggle this with the icon button in the footer.</p>`,
    },

    {
      layoutNumber: 5,
      position: { row: 3, column: 1 },
      offset: { x: 10, y: -15 },
      size: { width: 100, height: 85 },
      sizeType: 'grow',
      type: 'html',
      src: `<h2>A chance to give new life to an old idea...</h2>
      <p>It's actually a concept that was originally born back in the early noughties when I was last working as a web developer. For our new business myself and my colleague/friend developed a CMS that fed an advanced actionscript front-end to build pages out of elements that 'lived' within a 2.5d space.</p>`,
    },
    {
      layoutNumber: 8,
      position: { row: 3, column: 2 },
      offset: { x: 50, y: -40 },
      size: { width: 20, height: 35 },
      sizeType: 'auto',
      clamp: 85,
      type: 'image',
      src: {
        src: '../JS.png',
        alt: `Javascript is one of my skills`,
      },
    },
    // {
    //   layoutNumber: 9,
    //   position: { row: 3, column: 2 },
    //   offset: { x: 50, y: -40 },
    //   size: { width: 20, height: 35 },
    //   sizeType: 'auto',
    //   clamp: 85,
    //   type: 'image',
    //   src: {
    //     src: '../React.png',
    //     alt: `React is one of my skills`,
    //   },
    // },
    {
      layoutNumber: 10,
      position: { row: 3, column: 2 },
      offset: { x: 50, y: -40 },
      size: { width: 20, height: 35 },
      sizeType: 'auto',
      clamp: 85,
      type: 'image',
      src: {
        src: '../CSS3.png',
        alt: `CSS is one of my skills`,
      },
    },
    {
      layoutNumber: 11,
      position: { row: 3, column: 2 },
      offset: { x: 50, y: -40 },
      size: { width: 20, height: 35 },
      sizeType: 'auto',
      clamp: 85,
      type: 'image',
      src: {
        src: '../HTML5.png',
        alt: `HTML is one of my skills`,
      },
    },
    {
      layoutNumber: 6,
      position: { row: 4, column: 2 },
      offset: { x: 3, y: -15 },
      size: { width: 95, height: 125 },
      sizeType: 'grow',
      type: 'html',
      src: `
      <h2>Life is for living, and learning</h2>
      <p>Having spent a while getting back up to speed with web development mainly through a course in React I decided that, for my portfolio, I wanted to rediscover some confidence with 'vanilla' HTML,CSS, and Javascript. This was originally reliant on the Flash player but I fell in love with the idea and decided I wanted to recreate it with the, massively matured, tools that are now available.</p><p>Each of these elements is built with a bit of 'personality' via a randomisation of various properties which is a method I enjoy using, I define some boundaries and then let my creations do their thing.</p>`,
    },
    {
      layoutNumber: 12,
      position: { row: 4, column: 1 },
      offset: { x: 20, y: 200 },
      size: { width: 80, height: 15 },
      sizeType: 'grow',
      type: 'title',
      src: `check out the <a href="https://github.com/gileswebberley/gilo-does-coding" target="_blank">source code</a> on GitHub`,
    },
  ],
};
export default WelcomeContent;
