const WildOasisContent = {
  pageId: 'Wild',
  buttonText: 'Project - Wild Oasis',
  aspectRatio: '16:9',
  content: [
    {
      layoutNumber: 1,
      position: { row: 1, column: 1 },
      offset: { x: 0, y: 0 },
      size: { width: 150, height: 35 },
      sizeType: 'auto',
      type: 'title',
      src: `Wild-Oasis - React/Styled Components/TanStack Query/Supabase/Stripe`,
    },
    // {
    //   layoutNumber: 2,
    //   position: { row: 1, column: 2 },
    //   offset: { x: 0, y: 0 },
    //   size: { width: 1, height: 1 },
    //   sizeType: 'fixed',
    //   type: 'blank',
    // },
    {
      layoutNumber: 3,
      position: { row: 2, column: 1 },
      offset: { x: 10, y: 10 },
      size: { width: 60, height: 80 },
      sizeType: 'auto',
      clamp: 250,
      type: 'image',
      src: {
        src: '../Wild-Oasis-desktop.jpg',
        alt: `screenshot of a page of my wild oasis project`,
      },
    },
    {
      layoutNumber: 4,
      position: { row: 2, column: 1 },
      offset: { x: 0, y: 20 },
      size: { width: 40, height: 35 },
      sizeType: 'auto',
      clamp: 170,
      type: 'title',
      src: `<a href="https://wild-oasis-demo.netlify.app/welcome" target="_blank">visit the live website</a>`,
    },
    {
      layoutNumber: 7,
      position: { row: 2, column: 2 },
      offset: { x: 0, y: 0 },
      size: { width: 100, height: 140 },
      sizeType: 'grow',
      type: 'html',
      src: `<h2>I came to this point through passion, but also necessity</h2>
      <p>After a cancer scare, being hospitalised with pneumonia, my wedding, and even learning offline editing so I could film and edit a mockumentary, I realised that I had a massive desire to get back into web development, and to get myself a new career that used my brain rather than battering my broken body. After speaking to old colleagues and researching the market I discovered that Javascript, which I had worked with and enjoyed a lot in the past, had continued to grow and that React was a popular library which had been developed with it; I decided learning React would therefore be a great way to get back upto speed with modern web development.</p>`,
    },

    {
      layoutNumber: 5,
      position: { row: 3, column: 1 },
      offset: { x: 10, y: -15 },
      size: { width: 100, height: 135 },
      sizeType: 'grow',
      type: 'html',
      src: `<h2>The outcome of throwing myself into it</h2>
      <p>I decided that I wanted some structure to my learning and so I jumped headfirst into taking part in a highly rated Udemy course. At the end of the course we had developed an admin system for an imaginary holiday cabin business and so I challenged myself to take what I'd learnt and develop the front-end to go with it (just as a way to add new bookings initially). Throughout the project I experimented with my own solutions and built some components from scratch as I came across a use for them and as a way to improve my understanding and skills. I also challenged myself to integrate an online payment system which took me into serverless functions with Node on Netlify.</p>`,
    },
    {
      layoutNumber: 8,
      position: { row: 3, column: 2 },
      offset: { x: 50, y: -40 },
      size: { width: 20, height: 35 },
      sizeType: 'auto',
      clamp: 85,
      type: 'image',
      src: {
        src: '../React.png',
        alt: `React is now one of my skills`,
      },
    },
    // {
    //   layoutNumber: 9,
    //   position: { row: 3, column: 2 },
    //   offset: { x: 50, y: -40 },
    //   size: { width: 20, height: 35 },
    //   sizeType: 'auto',
    //   clamp: 85,
    //   type: 'image',
    //   src: {
    //     src: '../React.png',
    //     alt: `React is one of my skills`,
    //   },
    // },
    {
      layoutNumber: 10,
      position: { row: 3, column: 2 },
      offset: { x: 50, y: -40 },
      size: { width: 20, height: 35 },
      sizeType: 'auto',
      clamp: 85,
      type: 'image',
      src: {
        src: '../react-query.png',
        alt: `TanStack Query is now one of my skills`,
      },
    },
    {
      layoutNumber: 11,
      position: { row: 3, column: 2 },
      offset: { x: 50, y: -40 },
      size: { width: 20, height: 35 },
      sizeType: 'auto',
      clamp: 85,
      type: 'image',
      src: {
        src: '../Styled Components.png',
        alt: `Styled Components is one of my skills`,
      },
    },
    {
      layoutNumber: 6,
      position: { row: 4, column: 2 },
      offset: { x: 3, y: -15 },
      size: { width: 95, height: 170 },
      sizeType: 'grow',
      type: 'html',
      src: `
      <h2>A massive course to get a great introduction to the React eco-system</h2>
      <p>The course has been a wonderful way to learn about all sorts of modern web development skills. I always leave myself learning notes in my code but I have also built a reference document based on this fabulous resource. We used CRA to get started but then moved onto Vite (which I've also used for this site's development) so have been using the Node Package Manager extensively. Alongside taking a deep dive into React, from all sorts of state-management to looking at React design patterns and how the rendering works, I have also been introduced to and used TailwindCSS, Redux (Classic and RTK), React-Router, Context API, and even an introduction to using Supabase as a database. You can <a href="https://github.com/gileswebberley/Ultimate_React_Course" target="_blank">check out all of the projects and notes</a> that I have created/worked on for this course on GitHub</p>`,
    },
    {
      layoutNumber: 12,
      position: { row: 4, column: 1 },
      offset: { x: 100, y: 0 },
      size: { width: 30, height: 90 },
      sizeType: 'auto',
      clamp: 100,
      type: 'image',
      src: {
        src: '../Wild-Oasis-mobile.jpg',
        alt: 'screenshot of the website on a mobile phone',
      },
    },
    {
      layoutNumber: 13,
      position: { row: 4, column: 1 },
      offset: { x: 20, y: 200 },
      size: { width: 80, height: 15 },
      sizeType: 'grow',
      type: 'title',
      src: `check out the Wild-Oasis <a href="https://github.com/gileswebberley/gilo-does-coding" target="_blank">source code</a> on GitHub`,
    },
  ],
};
export default WildOasisContent;
